image: registry.questioneer.dev/internal/containers/ci/poetry

stages:
- test
- test-multiversion
- build

before_script:
  - poetry config settings.virtualenvs.in-project true
  - poetry install

test-cov:
  stage: test
  script:
  - make test
  - make test-cov
  artifacts:
    paths:
    - htmlcov/
  cache:
    paths:
    - .venv/
    policy: pull

test-lint:
  stage: test
  script:
  - make lint
  cache:
    paths:
    - .venv/
    policy: pull-push

test-type:
  stage: test
  script:
  - make type
  cache:
    paths:
    - .venv
    policy: pull

test-3.6:
  stage: test-multiversion
  image: registry.questioneer.dev/internal/containers/ci/poetry-3.6
  script:
  - make test
  cache:
    key: "3.6"
    paths:
    - .venv/

test-3.7:
  stage: test-multiversion
  image: registry.questioneer.dev/internal/containers/ci/poetry-3.7
  script:
  - make test
  cache:
    key: "3.7"
    paths:
    - .venv/

# Due to ruamel.yaml, python 3.8 does not currently work.
# Therefore we have commented it out to speed up CI.

# test-3.8-rc:
#   stage: test-multiversion
#   image: registry.questioneer.dev/internal/containers/ci/poetry-3.8-rc
#   script:
#   - make test
#   cache:
#     key: "3.8-rc"
#     paths:
#     - .venv/
#   allow_failure: true

build:
  stage: build
  script:
  - poetry build
  artifacts:
    paths:
    - dist/
  cache:
    paths:
    - .venv
    policy: pull
